[theme]
base = "light"
primaryColor = "#171717"
backgroundColor = "#fafafa"
secondaryBackgroundColor = "#ffffff"
textColor = "#171717"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
